version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: f1_predictor
      POSTGRES_USER: f1user
      POSTGRES_PASSWORD: f1password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
